### ISSUE TITLE
Create Light Wallet Account Failing

### ISSUE THREAD

**Issue by rohanpatel2602** [gnosis/MultiSigWallet#101]
I'm getting the error "hdkeyring is not a constructor" upon attempting to create a light wallet

![image](https://user-images.githubusercontent.com/4909231/37878223-23acd5a8-3083-11e8-94af-872179b85ad0.png)

**Comment by rohanpatel2602** [comment]
Fixed - turns out it wasn't able to import eth-hd-keyring in properly.
Had to downgrade Node to 6.5.0, and then electron-rebuild scrypt with version 1.4.3

**Comment by jinxinslim** [comment]
Hi, i hava the same error, i have downgraded Node to 6.14.1 and electron to 1.4.3. Run electron . in the dapp dir, also this error, what wrong with it .
