### ISSUE TITLE
Bug when doing npm run test-dapp

### ISSUE THREAD

**Issue by yoscar1** [gnosis/MultiSigWallet#116]
Status in the MultiSigWallet route I run npm run test-dapp and it does not do anything, that is, it does not launch any sales in the browser and by the console what it tells me is this: 
![image](https://user-images.githubusercontent.com/18383745/38630432-ed2987ba-3d84-11e8-8ea0-bef50a85acbf.png) 
How do I try the wallet?
![image](https://user-images.githubusercontent.com/18383745/38631021-914cda3a-3d86-11e8-97da-7a59bd53c103.png)

**Comment by denisgranha** [comment]
Hello @yoscar1 the tests were designed to run in a Unix environment.

You can try the interface in https://wallet.gnosis.pm/#/wallets using one testnet with metamask, or a local testrpc.
