### ISSUE TITLE
Ledger Nano S support broken after firmware update

### ISSUE THREAD

**Issue by D-Nice** [gnosis/MultiSigWallet#118]
I've used the wallet via the interface just fine previously, while my Ledger was on firmware 1.4

In the meantime, some other people in the company have been having issues getting it to work at all. They were using Ledgers with the newest firmware. After upgrading to firmware 1.4.1, the only thing I can apparently do is deposit into wallets, everything else just shows an Error popup with the text `Invalid status 6a80`. Same goes when trying to deploy new wallets. This error occurs after I click confirm on my Ledger for the transaction.

EDIT: Mentioned this error popping up after clicking confirm for the tx, now in general, it appears it doesn't even request a confirmation, just gives invalid status. Sometimes might have a tx confirmation or even address confirmation, but if it gets that far, the Ledger is basically hanging.

**Comment by AmitShah** [comment]
Environment:
Gnosis MultiSigWallet 1.2.4 
Ledger Nano S firmware  Secure Element - 1.4.1 MCU - 1.5
Ethereum app 1.0.22

when signing any transaction the Error outputted is

Invalid signature received. Please update your Ledger Nano S.

**Comment by AmitShah** [comment]
@D-Nice I saw your error 6a80 when I didnt set the contract data to "Yes" in the Ethereum app.  Try to set that and see if the error changes

**Comment by D-Nice** [comment]
Just checked my Ledger, and turns out that may be the issue (as contract data was off). I guess I got lazy/careless with checking that setting. I'll retry and report back.

**Comment by D-Nice** [comment]
Ok, re-tested, and everything appears working again, after having re-enabled contract data, which was indeed the culprit.
