### ISSUE TITLE
Invalid signature received. Please update your Ledger Nano S.

### ISSUE THREAD

**Issue by AmitShah** [gnosis/MultiSigWallet#120]
Environment:
Gnosis MultiSigWallet 1.2.4
Ledger Nano S firmware Secure Element - 1.4.1 MCU - 1.5
Ethereum app 1.0.22

when signing any transaction the Error outputted is

Invalid signature received. Please update your Ledger Nano S.

**Comment by denisgranha** [comment]
I think you have disabled browser support? can you check?

**Comment by nithinkrishna** [comment]
I seem to be getting this error too, however only on my local geth testnet.
