### ISSUE TITLE
Token withdrawal gasPrice

### ISSUE THREAD

**Issue by pakokrew** [gnosis/MultiSigWallet#123]
Hey, 

Looks like it is missing the page to choose gas price & gas limit when we want to withdraw erc20 tokens from a wallet, like the one we have for all the others transactions.

The default estimation is a bit low so it is very hard to get the tx mined

thanks

**Comment by denisgranha** [comment]
Hello @pakokrew that issue has been solved in the last release https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.0 thank you for reporting
