### ISSUE TITLE
The dAPP cannot handle the non daily limit version of the multisig wallet

### ISSUE THREAD

**Issue by roderik** [gnosis/MultiSigWallet#13]
I deployed the version of the wallet without a daily limit, and the interface will not let me withdraw. It assumes the limit is 0, and that there is 0 limit left. 

If I use the console and just remove the disabled from the withdraw button, it works perfectly. I'm not into Angular, so I have no idea where to tweak this behaviour. There also does not seem to be a setting. 

Any idea's because while I have a functional workaround, it is not that smooth :)

**Comment by denisgranha** [comment]
Hey Roderik, thanks for testing out the interface.
It is intented to be used with the daily limit version of the wallet, but I think it should behave correctly also for the non daily limit wallet, we will add this in future releases

**Comment by roderik** [comment]
Nice thanks!

**Comment by denisgranha** [comment]
https://github.com/gnosis/MultiSigWallet/releases/tag/v1.1.1
