### ISSUE TITLE
Which version is used for the main net factory?

### ISSUE THREAD

**Issue by etiennetatur** [gnosis/MultiSigWallet#14]
I'm trying to verify my contract created from the main net factory located at
https://etherscan.io/address/0x12ff9a987c648c5608b2c2a76f58de74a3bf1987

I tried with the version and the compiler of v0.4.15, v0.4.13, v0.4.11 and no optimization with no success. 

Best,

**Comment by kennyrowe** [comment]
I have the same factory. Not sure it's legit!

**Comment by Sofoca** [comment]
The current factory contract "suggested" by the MultisigWallet-OSX binary is [`0xed5a90efa30637606ddaf4f4b3d42bb49d79bd4e`](https://etherscan.io/address/0xed5a90efa30637606ddaf4f4b3d42bb49d79bd4e#code) which is verifiable on Etherscan.

**Comment by denisgranha** [comment]
Sorry guys, I have tried to replicate the version used to deploy but couldn't get the contracts verified, it was deployed by me, so it's legit, but cannot replicate the configuration
