### ISSUE TITLE
1 error generated after npm i

### ISSUE THREAD

**Issue by ioleksiu** [gnosis/MultiSigWallet#140]
<img width="1037" alt="screen shot 2018-05-08 at 4 02 35 pm" src="https://user-images.githubusercontent.com/7544213/39758720-659c44a8-52d9-11e8-8404-b85f2d33b961.png">

**Comment by ccmawo** [comment]
I had the same issue. I was able to workaround it by downgrading nodejs from v10.1.0 to v8.11.2.

**Comment by giacomolicari** [comment]
@ioleksiu does the problem persist? Otherwise I will close the issue.
