### ISSUE TITLE
For release download checksums, use a hashing algorithm that is not broken (currently MD5)

### ISSUE THREAD

**Issue by AronVanAmmers** [gnosis/MultiSigWallet#141]
MD5 is broken`*`, please don't use it for download checksums for this highly security-sensitive piece of software. Switch to something secure like SHA-256.

`*` Generating pairs of colliding files is [trivial](http://www.win.tue.nl/hashclash/). A preimage attack for MD5, i.e. generating a file that has an arbitrary MD5 hash (like the hash of an existing file as used in download checksums), is still considered unpractical, so it could be argued that MD5 still safe to use as a download checksum. However since MD5 has been broken in other areas, that makes it vulnerable to types of attacks that something like SHA-256 would not, and it's not unlikely that a preimage attack will be practical in the near future. Better be safe than sorry.

**Comment by denisgranha** [comment]
I agree, but unfortunately there are no default command line sha2 commands like for md5 in mac and linux. You can see geth also adds the md5, I imagine for pragmatism

**Comment by denisgranha** [comment]
https://github.com/ethereum/go-ethereum/issues/15315

**Comment by AronVanAmmers** [comment]
Interesting that Geth uses MD5 for download checksums too. They do however offer PGP signatures for every release too, so users have a much stronger way to check file integrity and origin. Adding that would be even better than just switching the hashing algorithm.

And there _are_ built in commands in Windows, Linux and Mac OS to generate SHA-256 checksums:

- Windows: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil#BKMK_hashfile (e.g. `certutil -hashfile [filename] sha256`)
- Mac OS: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/shasum.1.html (e.g. `shasum -a 256 [filename]`)
- Linux (practically all recent distributions): https://www.systutorials.com/docs/linux/man/1-sha256sum/ (e.g. `sha256sum [filename]`)

**Comment by denisgranha** [comment]
Thanks @AronVanAmmers 

In the last releases we added sha256 instead of MD5

https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.5
