### ISSUE TITLE
"GET /partials.js" Error (404): "Not found"

### ISSUE THREAD

**Issue by ioleksiu** [gnosis/MultiSigWallet#142]
<img width="906" alt="2018-05-10 21 08 12" src="https://user-images.githubusercontent.com/7544213/39885883-7fb7d578-5496-11e8-96c6-8809e2e2d633.png">
<img width="1006" alt="2018-05-10 21 08 28" src="https://user-images.githubusercontent.com/7544213/39885890-826ee298-5496-11e8-9817-5d11e153e858.png">

**Comment by denisgranha** [comment]
those files are automatically generated when running npm install
