### ISSUE TITLE
Can't interact with Ledger Wallet

### ISSUE THREAD

**Issue by ioleksiu** [gnosis/MultiSigWallet#145]
<img width="1133" alt="2018-05-16 14 20 58" src="https://user-images.githubusercontent.com/7544213/40114846-08c06392-5917-11e8-8cb3-b38636e69a64.png">
<img width="1551" alt="2018-05-16 14 15 44" src="https://user-images.githubusercontent.com/7544213/40114849-0d186f20-5917-11e8-927b-b408373ea4df.png">

The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null')

**Comment by denisgranha** [comment]
Are you over https?
