### ISSUE TITLE
submitTransaction to have ownerExists modifier as internally it uses confirmTransaction that has such modifier?

### ISSUE THREAD

**Issue by stefek99** [gnosis/MultiSigWallet#146]
### `submitTransaction`

https://github.com/gnosis/MultiSigWallet/blob/516cfcd0cd8b53112c7bf8869226ebabb2035379/contracts/MultiSigWallet.sol#L189

### `confirmTransaction`
https://github.com/gnosis/MultiSigWallet/blob/516cfcd0cd8b53112c7bf8869226ebabb2035379/contracts/MultiSigWallet.sol#L199

Please confirm it is desired and I'll create a pull request.

**Comment by cbruguera** [comment]
My understanding of the code is that precisely because the internal call makes the validation, it's not necessary to make it on the external method... (Still seems a bit weird to allow anyone make submission calls to the contract)

**Comment by stefek99** [comment]
Here is real-life example: https://blog.aragon.one/introducing-the-aragon-community-multisig-348a69d16374

![image](https://user-images.githubusercontent.com/249703/42474322-22c3e048-83bf-11e8-9875-217fbdb3d80f.png)

I think that anyone should be able to submit a transaction.

I think that if a submitter is a multisig keyholder then no need auto-approval.

(could be a perfectly valid use case for an admin who is keyholder to submit a proposal they don't want to approve)

Talk is cheap, show me the code, 1000 other priorities...

**Comment by Georgi87** [comment]
The internal call always does the validation. This is why the `submitTransaction` function doesn't use the `ownerExists` modifier. However, I agree that in terms of code readability it would be better to include the modifier also in the `submitTransaction` function.
