### ISSUE TITLE
User interface not loading in the case of ethgasstation hosting issues

### ISSUE THREAD

**Issue by miohtama** [gnosis/MultiSigWallet#148]
MultiSigWallet Angular app is using the following resource https://ethgasstation.info/json/ethgasAPI.json

In the case ethgasstation.info is down (now HTTP 522, connection timeout), the user interface is not loading when clicking open a wallet. You get the following console error(s):

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/49922/40320276-608a3af4-5d2b-11e8-890c-aac16925d73f.png">

The main screen of the listing all wallets is not affected.

How to repeat

* Block ethgasstation.info domain or wait it going down
* Click to open any of multisig wallets
* Past transactions and wallet balance is not loaded, the console shows error

Suggested solutions

* Do not depend on UI of having ethgasstation available - soft fail in the case of JSON data from there could not be loaded within a reasonable timeout (1s)
* Fallback to hardcoded gas info 
* Use the user wallet, e.g., MetaMask gas estimation

**Comment by mkoistinen** [comment]
I have a related issue. It seems when using this wallet (even light use), I get rate-limited from EthGasStation.info, this then results in confusing, inconsistent state without error messages. I wonder if the dapp could be more conservative with calls to EthGasStation?

**Comment by FransTwisk** [comment]
Experiencing exactly the same thing... Any workaround for now?

**Comment by giacomolicari** [comment]
Thanks for reporting the issue, it will be fixed with the next release as soon as possible.

**Comment by denisgranha** [comment]
We added a fallback against default web3 gas price. In a next release we will point to our own gas station, with proper availability.

Sorry for the inconvenience. It's live now and also in electron https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.5
