### ISSUE TITLE
App: Cannot restore wallet because cannot paste in address on OSX

### ISSUE THREAD

**Issue by miohtama** [gnosis/MultiSigWallet#151]
For some reason Address input field does not accept CMD+V paste here:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/49922/40540181-83e66696-6017-11e8-8192-dab83de4681c.png">

This is the latest OSX app. As a sidenote looks like one cannot confirm version number of the app inside the app from anywhere.

I double checked, I can paste the same clipboard content to other applications and it should be plain text. Maybe some Electron issue?

**Comment by mkoistinen** [comment]
Indeed, the CMD-Paste doesn't seem to work, but I'm able to CTRL-click (or right-click) and choose Paste from the context menu.

Hope this helps.

**Comment by denisgranha** [comment]
So the problem was the electron app was supporting ctrl+c/v but not cmd based. New release fixes this issue https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.5

Thanks

**Comment by jtremback** [comment]
This seems to still be an issue on 1.3.7
