### ISSUE TITLE
ethggasstation cloudflare rate limit breaks the desktop wallet

### ISSUE THREAD

**Issue by alexanderanter** [gnosis/MultiSigWallet#155]
When I get temporarily banned by ethgasstation.info through their cloudflare, it breaks the functionality of the gnosis multisig desktop wallet.

Seems like ethgasstation.info got very strict rate limiting on the site and its quite easy to get temporarily banned.

I think the wallet should still be able to function and just not utilize the gas prices from ethgasstation when the client is unable to connect...

**Comment by denisgranha** [comment]
This should be already solved with version >= 1.3.5

What platform are you running on?

**Comment by Snuff** [comment]
Hi @denisgranha, same issue with web version. https://wallet.gnosis.pm
