### ISSUE TITLE
The onlyWallet blocking me from interact contract on truffle console

### ISSUE THREAD

**Issue by ChanPoyu** [gnosis/MultiSigWallet#157]
I was trying to interact with the wallet contract through truffle console and some errors just occurred.

I tried to send transaction by using the ` addOwner(new_owner_address) ` function. It just won't let me do it.

I tried another function ` getOwner() ` and it run finely.

Finally I figure out the functions with the modifier ` onlyWallet`  blocked my operation(since i comment out the modifier and the functions worked normally).

I know It will probably cause a security vulnerability if I'm not using the ` onlyWallet ` modifier.

According to the code I need to find someway to make my msg.sender == address(this) the contract address.

Do anyone have a solution of this issue.

**Comment by ChanPoyu** [comment]
I changed the code and work well.
https://gist.github.com/ChanPoyu/2350b0c9f3e1b5c2742061357ba25e98

**Comment by denisgranha** [comment]
Hello @ChanPoyu the main point of a multisig, it's to have transactions signed by all the required owners, that modifier it's on purpose, only the wallet can do a multisig transaction, that means, it will only get triggered when the wallet has enough consensus:
1. You submit the transaction https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L189 where:
* to is the multisig address
* data is the function addOwner codified
2. You confirm the transaction with the other owners
3. The transaction get's executed when the owner N confirms the tx, being N the number of required confirmations
