### ISSUE TITLE
Vulnerability for chain reorg

### ISSUE THREAD

**Issue by yaronvel** [gnosis/MultiSigWallet#17]
The confirmation per transaction index makes the wallet vulnerable to chain reorg (i.e., when block becomes orphan).
The following scenario illustrates the problem:
1. Bob and Alice makes 2-out-of-2 multisig.
2. Bob submit a transaction to pay 1 eth as a donation to children hospital.
3. Alice see the transaction on etherscan/gnosis UI and confirms it (without waiting for 6 blocks confirmation).
4. Bob mines a longer chain where item 2 never happened, and instead in item he submit a payment for 100 eth to himself.
5. Bob resubmit Alice confirmation and run away with the 100 eth.

IMO, you should warn users to wait for 6 (or whatever) blocks before confirming a transaction.
As these days it is almost amount to 3 minutes, I doubt anyone is doing it.

**Comment by denisgranha** [comment]
Considering there is no notification for users about new tx's awaiting for being confirmed, that tx's takes long to be mined, that difficulty is above TH/s
I would say, that inherits from PoW blockchains, all Dapp users should know that there is no finality for transactions

All multisig should have trusted owners too

**Comment by yaronvel** [comment]
What you are saying is simply not true. U should idenify transaction according to parameters hash and not id.
I already explained it to your cto.
Please consult with him.

**Comment by denisgranha** [comment]
We are using an incremental nonce for allowing easy signing for offline transactions, to avoid copying an entire hash

In the next version of the multisig, https://github.com/gnosis/gnosis-safe-contracts we use the hashes

**Comment by yaronvel** [comment]
ok, so it is a real issue.
