### ISSUE TITLE
MultisigWalletWithDailyLimit allows ETH transactions ignoring the required confirmations

### ISSUE THREAD

**Issue by cbruguera** [gnosis/MultiSigWallet#175]
Contrary to the base `MultiSigWallet` contract, `MultiSigWalletWithDailyLimit` overwrites the confirmation check and **ignores** the `required` parameter set for multisig transactions (it passes as long as the transaction is below the daily limit). What's the rationale for ignoring this parameter for contracts with daily limit? In this case, only contract calls are required to comply with the number of confirmations, but it seems to me that in this way it's not much of a "multi-sig" wallet if such threshold is entirely ignored, especially since transfer of ETH is one of the main functionalities of wallets.

**Comment by denisgranha** [comment]
That's the purpose of Daily limit, to allow withdraw of small amounts (under daily limit) to be done with only one confirmation, and withdraws above that limit, to be confirmed by all required owners.

You can also set the daily limit to 0 and all ETH transfers need to be confirmed by all required owners
