### ISSUE TITLE
Feature request: enable copying the wallet address

### ISSUE THREAD

**Issue by oleiba** [gnosis/MultiSigWallet#18]
Very simple and straight-forward feature: copy the account address.
It seems that currently, there's no easy way to do it.

**Comment by denisgranha** [comment]
What OS are you using?

**Comment by sillytuna** [comment]
OSX - neither copy or paste work from keyboard shortcuts, only from the context menu.

**Comment by denisgranha** [comment]
https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.5
