### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [gnosis/MultiSigWallet#181]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by denisgranha** [comment]
Hello @anharismail thank you for the offer :) 
We already have a second version of the multisig, with better UI designs https://blog.gnosis.pm/announcing-the-gnosis-safe-beta-personal-edition-19a69a4453e8

But feel free to contribute to this current project
