### ISSUE TITLE
Audit status

### ISSUE THREAD

**Issue by postables** [gnosis/MultiSigWallet#187]
Hello, just wondering what kind of audit, if any, has been performed?

**Comment by denisgranha** [comment]
* https://blog.gnosis.pm/the-gnosis-multisig-wallet-and-our-commitment-to-security-ce9aca0d17f6
* https://blog.zeppelin.solutions/gnosis-multisig-wallet-audit-d702ff0e2b1e

**Comment by postables** [comment]
Thank you
