### ISSUE TITLE
Why was usage of SafeMath excluded and other things such as uint, instead of uint256?

### ISSUE THREAD

**Issue by postables** [gnosis/MultiSigWallet#188]
I'm interested in using this wallet, however have been doing my own audit. After running mythril, and oyente many, many overflow and underflows were detected, which can easily be avoided through the use of safemath.

Here is an example output from mythril:
```
==== Integer Overflow ====
Type: Warning
Contract: MultiSigWallet
Function name: _function_0xa8abe69a
PC address: 1522
A possible integer overflow exists in the function `_function_0xa8abe69a`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: MultiSigWallet.sol:380

function getTransactionIds(uint from, uint to, bool pending, bool executed)
        public
        view
        returns (uint[] _transactionIds)
    {
        uint[] memory transactionIdsTemp = new uint[](transactionCount);
        uint count = 0;
        uint i;
        for (i = 0; i<transactionCount; i++) {
            if (pending && !transactions[i].executed || executed && transactions[i].executed) {
                transactionIdsTemp[count] = i;
                count += 1;
            }
        }
        _transactionIds = new uint[](to - from);
        for (i = from; i<to; i++) {
            _transactionIds[i - from] = transactionIdsTemp[i];
        }
    }

```

I can see under certain circumstances that particular things won't ever overflow,  however this particular function amongst others seem absolutely possible to overflow. Furthermore formatting semantics deviate highly from community accepted standards. Along with that are general inoptimizations such as using `uint` everywhere, instead of  `uint256`, along with using deprecated syntax. Is there any particular reason why these, especially use of SafeMath were omitted?

Would a PR be accepted that changes these inoptimizations, and standard deviations?

**Comment by Georgi87** [comment]
All math operations were carefully checked and validated. There is no case where an overflow is practically possible. The `getTransactionIds` function is purely for frontend purposes using `eth_call` and is no security concern. `uint` is just an alias to `uint256`. Generally the Syntax is not up to date with latest solidity changes as changes to code should be minimal at this point. We are also working on a complete redesign, which can be found here: https://github.com/gnosis/safe-contracts
