### ISSUE TITLE
Purpose of onlyWallet

### ISSUE THREAD

**Issue by Bookstore3** [gnosis/MultiSigWallet#189]
Hi,
I've been studying the MultiSigWallet.sol and found a modifier below.

```Solidity
modifier onlyWallet() {
  if (msg.sender != address(this))
    revert();
     _;
  }
```

and I've seen this modifier used on functions like addOwner or changeRequirement etc.

What I wondered was the difference between modifier above with the keyword "internal".

I know that the internal is like a private visibility but can be called only through inside wallet.

But the modifier above is public mixed with internal cause the only one that can call the function with the modifier is from the wallet due to the 'address(this)'.

A person can't call those function directly, even though the functions are visible.
Then, why do the functions with 'onlyWallet' modifier have visibility of the public?

I would like to know the reason behind this.

Thanks.

**Comment by shun-tak** [comment]
Please see this issue https://github.com/gnosis/MultiSigWallet/issues/157

If you want to call `addOwner`, use `submitTransaction` like this:
https://github.com/gnosis/MultiSigWallet/blob/v1.3.7/test/javascript/testExecutionAfterRequirementsChanged.js#L28-L34
