### ISSUE TITLE
Feature request: enable withdrawing ether from wallet, even without daily limit

### ISSUE THREAD

**Issue by oleiba** [gnosis/MultiSigWallet#19]
It seems that the wallet UI enables withdrawing some ether amount, only if my chosen contract is the extended multisig wallet with daily limit (as MultiSigWalletWithDailyLimit.sol).
We perfer not to use that - because this contract allows *any* owner to withdraw, and we want to keep this possibility with the same "m out of n" signatures constraint just as any other outgoing transaction.

Currently, my only option to withdraw ether when using the minimal MultiSigWallet contract (without the daily limits) - is to send multi-sig transaction to "submitTransaction" and to send some ETH amount with it.
So, it would be best to have another withdraw button which abstracts away this requirement.

**Comment by denisgranha** [comment]
Hello @oleiba 
You can also set daily limit so always needs approval but it's updated on the last version now
