### ISSUE TITLE
No new Windows releases, why?

### ISSUE THREAD

**Issue by ironboy1** [gnosis/MultiSigWallet#190]

**Comment by edmhs** [comment]
Any new Windows release yet?

**Comment by ironboy1** [comment]
well, all new releases since version 1.2.3 (March 2018) are just available for Linux and MacOS. I'm just wondering why....

**Comment by denisgranha** [comment]
Good morning, Windows build is broken by some dependencies, we are working on solving it, If you want to help us, feel free to open a PR

Apologies for the inconvenience

**Comment by giacomolicari** [comment]
Hi @edmhs @ironboy1 ,
[here](https://github.com/gnosis/MultiSigWallet/releases/tag/v1.3.7) you can find the Windows release v1.3.7.
