### ISSUE TITLE
How to call addowner()

### ISSUE THREAD

**Issue by a186r** [gnosis/MultiSigWallet#196]
i cant call addowner() function , Because I don't have that wallet private key ,  what should i do ?

**Comment by shun-tak** [comment]
Please see this issue https://github.com/gnosis/MultiSigWallet/issues/157

If you want to call `addOwner`, use `submitTransaction` like this:
https://github.com/gnosis/MultiSigWallet/blob/v1.3.7/test/javascript/testExecutionAfterRequirementsChanged.js#L28-L34

**Comment by a186r** [comment]
> Please see this issue #157
> 
> If you want to call `addOwner`, use `submitTransaction` like this:
> https://github.com/gnosis/MultiSigWallet/blob/v1.3.7/test/javascript/testExecutionAfterRequirementsChanged.js#L28-L34

thank you very much

**Comment by shun-tak** [comment]
@a186r You're welcome. If it turned out well, please close a issue.
