### ISSUE TITLE
`executeTransaction` replay attack

### ISSUE THREAD

**Issue by yaronvel** [gnosis/MultiSigWallet#2]
Further to my [previous report](https://github.com/ConsenSys/MultiSigWallet/issues/81).
The fact that `executeTransaction` is callable by anyone gives rise to real attacks.
Consider this scenario:
1. An ICO contract where admin can pause and resume sale.
2. Admin is a 1-out-of-2 multisig. I.e., there are 2 admins. Each can pause and resume sale.
3. When calling `pause` the function throws if already in pause mode.

Potential attack I:
1. ICO must be paused and both admins call the `pause` function. (Second call fails).
2. Admin fixes some things in the ICO and resumes it.
3. Malicious attacker calls `executeTransaction` for the second call. As a result, the ICO is paused.

Potential attack II:
ICO with different prices and a cap for every price.
User participates in an ICO with price 7, but exceeds cap and tx fails.
After 1 day, a new cap for price 8 is allocated.
User tx can be replayed and force him to buy with higher price.
In theory, this could happen even before user had the chance to revoke his tx.

**Comment by denisgranha** [comment]
Hello @yaronvel , thank you for taking time of reading the code and trying it out :)
ExecuteTransaction cannot be executed by anyone, only by MultiSig owners: https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L236

**Comment by yaronvel** [comment]
Is this a bug fix?
It is not the case here for example:
https://etherscan.io/address/0xd20e4d854c71de2428e1268167753e4c7070ae68#code

**Comment by denisgranha** [comment]
you are right, not sure in which commit it was changed but now is not allowed to be sent by anyone
