### ISSUE TITLE
Clicking a wallet in web dApp does not return any balance or transaction information

### ISSUE THREAD

**Issue by rogerdsx** [gnosis/MultiSigWallet#200]
Upon clicking a wallet, its balance and transaction information should be displayed. The information is initially not displayed and only displays whenever we click pending or executed filter and click back the all filter.

**Expected Behavior**:

![image](https://user-images.githubusercontent.com/34466964/45937082-b637cf80-bfef-11e8-9d65-a08052e95606.png)

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/34466964/45937043-88eb2180-bfef-11e8-95be-6573f31c327b.png)

**Comment by dpentajeu** [comment]
Same here. Please FIX this!!!

**Comment by denisgranha** [comment]
Hello both, what version are you using? 

Web, Mac, Windows, Linux?

**Comment by dpentajeu** [comment]
I'm using Chrome version, with metamask, ropsten network.

**Comment by rogerdsx** [comment]
Hey @denisgranha ! Yes! I use chrome MetaMask. Tried again today and it does not work for Executed and Pending filter as well.

![image](https://user-images.githubusercontent.com/34466964/45988472-bc8a8200-c0a9-11e8-9b73-f789b619df95.png)

![image](https://user-images.githubusercontent.com/34466964/45988479-c613ea00-c0a9-11e8-9297-cef17545f380.png)

**Comment by giacomolicari** [comment]
Hi @rogerdsx ,
I'm taking care of your issue, could you please provide more details like whether there are errors on the browser console and on what chain (Mainnet, Rinkeby, Kovan, Ropsten, localhost) you're experiencing the problem?

Thank you

**Comment by dpentajeu** [comment]
Hi all, just to update my status. I can access my multi-sig wallet already (using chrome + metamask). I'm going to try Trezor later. Just a suggestion, is it possible to show the multi-sign contract transaction in IN / OUT, so that I don't need to view via explorer?

**Comment by rogerdsx** [comment]
Hi @giacomolicari!

Thank you very much! There were errors on the browser console for Kovan and Privatenet initially but seems likes its all resolved.

Initially, I was not able to view the account address I was using, its balance and nonce etc. Also, the "All" filter in MultiSig Transactions didn't work. But its working fine now. 👍 

![image](https://user-images.githubusercontent.com/34466964/46123012-a1a54280-c24e-11e8-921f-61bc4a10e7bb.png)

@dpentajeu - Is the browser multisig wallet working well for you now?

**Comment by dpentajeu** [comment]
@rogerdsx Yes, it is working fine now! Strange behavior on the date we reported but all good now.

**Comment by giacomolicari** [comment]
Hi @rogerdsx ,
the issue might have happened due to network issues with the Ethereum provider. I'm glad everything is working fine now :)
