### ISSUE TITLE
dailyLimit isn't restrictive enough

### ISSUE THREAD

**Issue by BrendanChou** [gnosis/MultiSigWallet#201]
`dailyLimit` can be changed instantly by the wallet signers, so it does not actually provide any practical limit to the amount of Eth that is able to be moved within a day. Recommend removing the versions of MultisigWallet that have a daily limit. These contracts add more gas costs and complexity without adding any security.

**Comment by andreafspeziale** [comment]
I've been playing around with the MultiSig using the UI on Ropsten.

I've create at `t0` a MultiSig account adding 3 signers, filling it with some Ether and without any daily limit withdraw.
After that with one of the 3 signers I've submitted a request to set a daily limit of 10.
I've accepted the thing with all the signers.
After all the transaction were accepted I've tried to withdraw more than the limit and I've been able to do it more than once.

The address of the multisig on Ropsten:
`0xdaac420a3ea327026bd4b683123a644e53d56660`

**Comment by denisgranha** [comment]
The daily limit is not a limit of withdraws, it's a limit upon which you can perform multisig transactions with only one signature.
E.g daily limit of 10 ETH

1. Perform one multisig tx of 1 ETH, only requires one signature
2. Perform a second one of 9 ETH, it's below the limit, only one signature
3. Perform a third tx of 1 ETH, will need all signatures required. Already reached "limit" of 10ETH
