### ISSUE TITLE
Use wallet for ethereum classic

### ISSUE THREAD

**Issue by dhruvilshah88** [gnosis/MultiSigWallet#203]
I am currently using this wallet for ethereum, is it possible to point to web3 of ethereum classic and use this wallet for ethereum classic chain?

**Comment by denisgranha** [comment]
You can deploy the contract in any evm compliant chain

**Comment by denisgranha** [comment]
the interface will use a factory for the known chains: Mainnet (ETH), rinkeby, kovan and ropsten
And directly deploy the contract for others, it could be ETC.
