### ISSUE TITLE
1.4.0 Release

### ISSUE THREAD

**Issue by arthurk** [gnosis/MultiSigWallet#217]
I saw that the 1.4.0 release is already done in master, when can we expect the binaries to download?

**Comment by fred** [comment]
Looking forward for this release binaries.

**Comment by giacomolicari** [comment]
Hello everyone :)

The release 1.4.0 is available here: https://github.com/gnosis/MultiSigWallet/releases/tag/v1.4.0
Web: https://wallet.gnosis.pm
