### ISSUE TITLE
'npm run test-dapp' not work

### ISSUE THREAD

**Issue by kentarohorie** [gnosis/MultiSigWallet#221]
I don't know why but 'npm run test-dapp' not work.

> Chrome 71.0.3578 (Mac OS X 10.14.2) ERROR
>   Uncaught ReferenceError: angular is not defined
>   at app.js:3

Including modules maybe not work.

**Comment by rashijzeb** [comment]
What was the solution for this?

**Comment by kentarohorie** [comment]
@rashijzeb 
In my case, I was just wrong directory.
