### ISSUE TITLE
How to make an offline transaction

### ISSUE THREAD

**Issue by Levino** [gnosis/MultiSigWallet#222]
Hi all. I do not understand how to do an offline transaction. Is there any guide for this?

I have a 2 of 2 multisig wallet deployed on Kovan. Now I have signed a withdrawel transaction with a hot key on device 1. I now want to sign it with the cold key on device 2. I assume I can somehow create a transaction on device 1 which needs to be signed by the cold key and save it to a file. But I do not find a way to do it...

**Comment by denisgranha** [comment]
Hello @Levino 

Yeah, there are no docs about it and is not intuitive.

The process is the following, every multisig transaction have a nonce, that is a sequiential ID for each new multisig transaction. 

The first account needs to "add" the multisig transaction and the next owners, need to approve it trough "confirm" 

![screen shot 2019-01-23 at 10 49 58](https://user-images.githubusercontent.com/4806080/51597991-de333300-1efc-11e9-9428-7aca2cf6ea52.png)


After you have all the signed transactions, those are hexadecimal strings, you need to submit it to the network with the send signed transaction modal in Transactions section.

![screen shot 2019-01-23 at 10 52 23](https://user-images.githubusercontent.com/4806080/51598049-0327a600-1efd-11e9-98d6-33504ddea3fa.png)

Hope it helps

**Comment by Levino** [comment]
I see no button anywhere that says "add transaction" nor even "add *". Could you put in a screenshot of that button?

**Comment by Levino** [comment]
Here is a screenshot of my current wallet. I want to sign transaction 1 with the cold key.

![selection_077](https://user-images.githubusercontent.com/1150767/51598595-2acb3e00-1efe-11e9-8386-7abc93328e32.jpg)

**Comment by denisgranha** [comment]
Ah! the machine must be disconnected from internet :D

**Comment by Levino** [comment]
Which machine? Please be specific. I beg you! This is very hard. Thank you for helping. Maybe you can reach me through telegram: @LevinK

**Comment by denisgranha** [comment]
Your computer must be offline, so the multisig website / app will change from online mode to offline. New buttons will appear

**Comment by Levino** [comment]
Also I try to create the transaction on wallet.gnosis.pm. The site is not available when disconnected from the wifi / network.

**Comment by Levino** [comment]
I also tried multisigwallet standalone app. Which also does not work as expected. The standalone app on the hot machine does not have access to any of the keys which are allowed to cosign for this contract (because 1 key is in my metamask in chrome and the other key is on my ledger).

**Comment by denisgranha** [comment]
> I have done offline storage since armory. So this is how it goes in my world:
> 
> 1. Hot machine: Create a transaction which remains unsigned. You need to be online to create the transaction.
You can also sign the first transaction online and submit it
> 2. Hot machine: Save the unsigned transaction to usb stick
This is not a ring signature, but a smart contract signature, each owner signs a transaction, not a message, so what the owners sign is the id of the multisig transaction.
> 3. Cold machine: Read the unsigned transaction from the usb stick
> 4. Cold machine: Verify the transaction and sign it, then save the signed transaction to the usb stick
> 5. Hot machine: Read the signed transaction from the usb stick and broadcast it.
> 
> How on earth does it make any sense for the hot machine to be disconnected from the internet at any point in time?

**Comment by denisgranha** [comment]
Related with the website signing, you can download the website and open it offline
https://github.com/gnosis/MultiSigWallet/archive/v1.3.7.zip

```js
npm install 
npm start
```

If you find issues with the signing let me know, there might be updates on ledger, metamask that break the offline signing

**Comment by Levino** [comment]
I use 1.4.0. Is this maybe the issue?

**Comment by Levino** [comment]
So you are telling me that the cosigners just sign an integer? So there is no way to verify what they are signing on the offline machine (for example I would like to verify the recipients address of the transaction on the offline machine and be sure that it cannot be changed after signature).

**Comment by Levino** [comment]
Now I only get this
![selection_078](https://user-images.githubusercontent.com/1150767/51601946-feb3bb00-1f05-11e9-81a2-fecc95635d69.jpg)
and spinner in the upper right corner that never stops. Running v1.3.7 now.

**Comment by denisgranha** [comment]
> So you are telling me that the cosigners just sign an integer? So there is no way to verify what they are signing on the offline machine (for example I would like to verify the recipients address of the transaction on the offline machine and be sure that it cannot be changed after signature).

In this Wallet just, the Gnosis Safe contracts perform signing of messages, so you can always validate the parameters signed (Safe contracts are the next version of this contract, but doesn't have a interface for performing offline signing)

**Comment by denisgranha** [comment]
> Now I only get this
> ![selection_078](https://user-images.githubusercontent.com/1150767/51601946-feb3bb00-1f05-11e9-81a2-fecc95635d69.jpg)
> and a spinner in the upper right corner that never stops. Running v1.3.7 now.

Can you share your settings in the Settings section?

**Comment by denisgranha** [comment]
That's an open issue of all hardware wallets and ethereum wallets, how is displayed what you are actually signing. I hope with this EIP https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md when supported by major wallets and websites would provide better information for the user

**Comment by Levino** [comment]
I expected the offline version of the wallet dApp to verify the recipient of a transaction but for that it would need the state of the blockchain to query the actual parameters of the transaction with id x. I guess there is no way in ethereum to achieve real security here... It all boils down to:

a) The Hot machines must be virus free (at least the majority of them)
b) The rpc host the hot machines connect to must be trustworthy

The attack scenario I want to protect against is that the hot machines get virus infected and when someone wants to submit a transaction the recipients address is replaced by the virus. When the cosigners look at the transaction on their virus infected machines they see again the replaced address which looks good, but on the blockchain there is actually the attackers address. I understand that there is no way protecting against this attack.

**Comment by denisgranha** [comment]
You can use https://github.com/gnosis/safe-contracts/tree/v0.1.0 instead of this project, there you will have signing of metatransactions

**Comment by denisgranha** [comment]
Hey @Levino yes, that was initially one of the implementations. The problem there is more gas usage. If what you want is having to confirm explicitly all params, I recommend you taking a look at the Gnosis Safe.
1. https://gnosis-safe.readthedocs.io/en/latest/
2. https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L69
