### ISSUE TITLE
trezor support not working in App Version 1.4.0

### ISSUE THREAD

**Issue by bitcoinsSG** [gnosis/MultiSigWallet#223]
After changing web3 provider to trezor and clicking update, nothing happens.

This issue has been replicated on these configurations:

web interface + linux (ubuntu)
web interface + macOS
web interface + windows
desktop interface + linux (ubuntu)
desktop interface + macOS

**Comment by denisgranha** [comment]
Sorry for the inconvenience, this version solves that issues https://github.com/gnosis/MultiSigWallet/releases/tag/v.1.4.1

If you prefer, you can use Metamask in the web version and use Trezor/Ledger through MM
