### ISSUE TITLE
addOwner through submitTransaction

### ISSUE THREAD

**Issue by wa1era** [gnosis/MultiSigWallet#227]
Hi all!
I'm trying to add the fourth owner of the wallet.
I create **submitTransaction()** from the first owner to address MultisigWallet with the data: bytes "0x7065cb4800000000000000000000000000709dc0a8c840aa2321bee92ae4dbe5cf06199c"
![image](https://user-images.githubusercontent.com/44460825/53084380-8bac5d00-3522-11e9-9d52-26f696e4cc76.png)

Event Creates:
![image](https://user-images.githubusercontent.com/44460825/53084461-b4cced80-3522-11e9-9b77-7c6820e48bf5.png)
Trying to **confirmTransaction()** of the second owner
![image](https://user-images.githubusercontent.com/44460825/53084550-e04fd800-3522-11e9-8fba-1937fae21628.png)
But an error occurs and the fourth owner is not added.
![image](https://user-images.githubusercontent.com/44460825/53084701-33298f80-3523-11e9-92fd-b49583625a31.png)
Tell me, please, why is it impossible? I need to add a fourth owner so that the other owners (2 of 3) can confirm this.

**Comment by denisgranha** [comment]
Hello @wa1era What wallet are you using to generate these txs? I think the issue is the last tx needs a bit more of Gas.

**Comment by wa1era** [comment]
I use the address of the first owner on which 100 ether.
![image](https://user-images.githubusercontent.com/44460825/53087073-2491a700-3528-11e9-9d87-4022a1b2dd2d.png)
The other owners also have 100 ethers.
![image](https://user-images.githubusercontent.com/44460825/53087165-5145be80-3528-11e9-8fb6-df1e6dfd3177.png)

**Comment by wa1era** [comment]
> Hello @wa1era What wallet are you using to generate these txs? I think the issue is the last tx needs a bit more of Gas.

**Comment by denisgranha** [comment]
Ah you are using a testnet.

Yes, ether should not be the problem but the gas sent in the transaction. The last transaction needs to do an internal call to the multisig contract, estimation of gas must no be correct in the wallet you are using, so I would suggest you to set a gas amount of 400000 .

Is that the Mist wallet?

**Comment by wa1era** [comment]
Thank you very much! You really helped!
Put the gas at 400,000 and everything turned out!
![image](https://user-images.githubusercontent.com/44460825/53088832-bac7cc00-352c-11e9-8ae5-439972af9040.png)

It is strange that the wallet does not automatically calculate the gas.
![image](https://user-images.githubusercontent.com/44460825/53088307-290b8f00-352b-11e9-8eb6-2024124edf4b.png)

Wallet Parity-UI.
