### ISSUE TITLE
Changing gasPrice in settings does not take effect until after restart

### ISSUE THREAD

**Issue by konradkonrad** [gnosis/MultiSigWallet#23]
Affected version:
- [standalone multisigweb on linux](https://wallet-website.gnosis.pm/downloads/Ubuntu16-x64.deb)
- testing done offline with "LightWallet" settings

Steps to reproduce:
- create two wallets (not sure if one is sufficient)
- change `gasPrice` in `Settings` tab
- click `UpdateSettings`

Expected behavior:
- a `Confirm Offline` transaction for a wallet should have the `gasPrice` from settings applied

Experienced behavior:
- a `Confirm Offline` transaction for a wallet uses the `gasPrice` from before the change
- after restarting `multisigweb`, the new `gasPrice` is in effect

**Comment by vrolland** [comment]
Hello,

I actually fixed it on my local version by modifying two function in "dapp/services/Wallet.js" :
`      wallet.updateGasPrice = function (cb) {`
`          cb(null, txDefault.gasPrice);`
`      };`

`      wallet.updateGasLimit = function (cb) { `
`          cb(null, txDefault.gasLimit);`
`      };`

This will avoid the initialization of 
- the gasPrice to the network default
- the gasLimit to 90% of the gasLimit of the last block

Instead, it will set up the gasPrice and the gasLimit to the default given by the user.

I don't guarantee that there is no side effect, but it does the job.

Best,

**Comment by iivvoo** [comment]
Restarting seems to have no effect. The entered gasprice / gaslimit seems unrelated to what I see in the final transaction. This means that if a transaction fails the price can be rather high (I had a failed transaction that cost me $41)

**Comment by denisgranha** [comment]
This issue has been solved https://github.com/gnosis/MultiSigWallet/issues/30

**Comment by vogelito** [comment]
I just had this issue with 1.3.6 in offline mode and had to restart the software for it to take effect
