### ISSUE TITLE
Salary Distribution Through Multisig?

### ISSUE THREAD

**Issue by hanyoonLDA** [gnosis/MultiSigWallet#238]
Hello, just want to begin by saying that we love your multisig wallet -- simple and easy to use.

However, it's a bit tedious sending out salaries to a dozen addresses one by one. Is there a way to prepare multiple withdrawals with one transaction?

**Comment by tschubotz** [comment]
Hi Han, 
Unfortunately, there is no built-in way to simplify that with the current interface afaik. This could be a potential feature for the Gnosis Safe Team edition though, the soon to be successor of the Gnosis MultiSig. It is not yet on the roadmap as there are many other things to do.

Nevertheless, anyone could write an extension using the multi_send library enabling your desired behavior (https://github.com/gnosis/safe-contracts/blob/development/contracts/libraries/MultiSend.sol)

Hope this helps
