### ISSUE TITLE
Infura new API endpoint not connecting

### ISSUE THREAD

**Issue by galacticFlaneur** [gnosis/MultiSigWallet#239]
![image](https://user-images.githubusercontent.com/11600777/55163495-493cf800-5140-11e9-9ec3-b82e7e363e79.png)
![image](https://user-images.githubusercontent.com/11600777/55163533-5823aa80-5140-11e9-85e4-05818362548a.png)

It appears that there wasn't an update for the v3 project id?

**Comment by giacomolicari** [comment]
Hi @galacticFlaneur ,
you can specify a custom Ethereum Node endpoint by selecting *Custom configuration* in the multisig's settings page, this would make the Ethereum node's field editable. Please write your new endpoint there.

In case you're using Metamask, or any injected provider, make sure to update the Ethereum Node URL directly in the Metamask settings.

**Comment by galacticFlaneur** [comment]
Even after updating the end point, I am having instability when trying to connect to mainnet wallets created. It seems like it occasionally will recognize the onchain wallet, then when I click into it loads blank.

![image](https://user-images.githubusercontent.com/11600777/55166291-3e389680-5145-11e9-9ee6-02b2b638699e.png)


![image](https://user-images.githubusercontent.com/11600777/55166254-295c0300-5145-11e9-8f08-78668b80bfcd.png)

**Comment by giacomolicari** [comment]
I think the project id is missing in your Infura URL. You should generate it on the Infura dashboard.

Then, click on **Wallet factory contract** and choose **0x6e95c8e8557abc08b46f3c347ba06f8dc012763f** for Mainnet.

Hope that helps.

**Comment by galacticFlaneur** [comment]
Fixed. Thanks!
