### ISSUE TITLE
MultiSigWallet confirmation event not being fired

### ISSUE THREAD

**Issue by jjalan** [gnosis/MultiSigWallet#24]
Hi Team,

I am facing an issue, hopefully someone can help out.

I have built an API in node js that allows to create multisig wallet (3 owners, with 2 confirmations) using the MultiSig Wallet Factory Contract. I have been able to create two such MultiSig Wallet contracts.

Source: https://github.com/jjalan/multisig-api-demo/blob/develop/index.js
Endpoint: https://multisig-api.herokuapp.com/

Using this, I have been able to create two wallets as follows:

Wallet 1 ( Balance 5.5 ETH at the time of writing):
https://ropsten.etherscan.io/address/0xffbc9db586f5bbe3b132710f25fb067b63d403c7

Wallet 2:
https://ropsten.etherscan.io/address/0x3bae9e019f3866ca76c8f606a9be957d48d6af15

Both of the wallet has a common owner: 0x4054Db09C41e787cF5014A453f91c71418faB9AF. Now, I am trying to initiate a transfer from Wallet 1 to Wallet 2.

This API exposes a POST end point 'send' which can be invoked as follows:

curl -is -data {destination: '0x3bae9e019f3866ca76c8f606a9be957d48d6af15', amount: 1} -X POST https://multisig-api.herokuapp.com/wallet/0xffbc9db586f5bbe3b132710f25fb067b63d403c7/send

It returns a valid transaction hash as follows:
ex:
{"txHash":"0xd929693b63a9c6b97f958c4a3fc03a9f24628cf6eba429290cdbd104bfaf5b58","createdAt":1507209860875,"_id":"59d6328426ea3600129002fd"}
Transaction details:
https://ropsten.etherscan.io/tx/0xd929693b63a9c6b97f958c4a3fc03a9f24628cf6eba429290cdbd104bfaf5b58

However, in order to store the transaction id which MultiSigWallet Contract creates to transfer the money from Wallet 1 to Wallet 2, I am listening to Confirmation event on Wallet 1 contract instance (even tried listening on Wallet 2 contract instance) as mentioned here:
https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol

But it is never fired even though the transaction is being mined successfully. The code where I am listening to event is Line 190.
https://github.com/jjalan/multisig-api-demo/blob/develop/index.js

Can someone please help on identifying the transaction that MultSig Wallet Contract fires whenever submitTransaction is called?

**Comment by se3000** [comment]
Do you know what version/commit you were using when you deployed it?

**Comment by denisgranha** [comment]
Seems that the tx https://ropsten.etherscan.io/tx/0xd929693b63a9c6b97f958c4a3fc03a9f24628cf6eba429290cdbd104bfaf5b58 had a failing state that's the reason why you didn't get any log
