### ISSUE TITLE
Can't see accounts tab anymore

### ISSUE THREAD

**Issue by realisation** [gnosis/MultiSigWallet#244]
On Mac OSX of the latest release, I tried to create a multisig wallet on the test network, then realized I selected Ropsten instead of Rinkeby, where my test ether was requested from. 

So I deleted the account that I created thinking that I would be able to create another account after switching networks. Maybe I switched networks before deleting the account. 

But now I can't see the accounts tab anywhere to create another account.

I even tried deleting my installation and re-unzipping, but it was still the same situation -- meaning the accounts tab was nowhere to be found, and I was still connected to whatever network I was connected to before deleting the multisigweb application and re-unzipping another version.

**Comment by giacomolicari** [comment]
Hi @realisation ,
you don't need to delete accounts when switching from one network to another, the account's address will remain the same, whereas the balance would change accordingly to the network.

Please to go to settings and make sure you have selected **Light Wallet** under **Web3 Provider** menu.

**Comment by realisation** [comment]
Oh that’s right too bad I didn’t think of that.

Went to settings, problem was that light wallet was not selected. Strange
though since I did not change that in the first place, I wonder what
happened there.

Thank you
