### ISSUE TITLE
Latest windows release invalid zip file 

### ISSUE THREAD

**Issue by realisation** [gnosis/MultiSigWallet#254]
When trying to open, windows says

```
Compressed (zipped) Folders Error

Windows cannot open the folder. 

The compressed folder 'blah/blah/blah/blah/rkf.exe.zip' is invalid.
```

This is true even though the checksum of the download is correct.

**Comment by cfravel** [comment]
I was able to unzip and run 1.5.0 for Windows from its zip file.
However, instead of having just the 1.5.0 exe in it, the zip file has a whole bunch of external .dll files and is huge.

**Comment by giacomolicari** [comment]
Thanks for reporting this, we will fix it asap.

**Comment by giacomolicari** [comment]
Hi @cfravel ,
I just updated Multisig windows v1.5.0 zip file, please check it out here: https://github.com/gnosis/MultiSigWallet/releases/tag/v1.5.0

Thank you
