### ISSUE TITLE
Privacy Policy isn't available

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/MultiSigWallet#265]
The Privacy Policy seems to be unavailable. In the footer of the page it is not able to be clicked, and in the pop up to accept it, when entering for the first time, it is, but the links redirects the user to the main page of gnosis.io. 

**A. Steps to reproduce:**
1. Go to wallet.gnosis.pm for the first time
2. Click on the Privacy Policy link which appears on the pop-up.
3. Observe

*Expected behavior*
The user is correctly redirected to the Privacy Policy link.

*Actual behavior:*
The user is redirected to the main page of Gnosis.io.

*Screenshot*
https://drive.google.com/open?id=1W_gA6OkQTwAa04s0tDKHS-MOf4SDZ8il

**B. Steps to reproduce:**
1. Go to wallet.gnosis.pm
2. Try to click on the Privacy Policy link.
3. Observe

*Expected behavior*
The user can click the link, and is correctly redirected to the Privacy Policy.

*Actual behavior:*
The Privacy Policy is not able to be clicked.

*Screenshot*
https://drive.google.com/open?id=1_2jj0aV8uZU7MvNeVIF9UY5hPT00xPrc

**Comment by giacomolicari** [comment]
Thank you @MicaelaPesado for reporting it, we just deployed a fresh version that fixes the problem.
It will be available also on the desktop version in the following days.
