### ISSUE TITLE
gnosis.pm doesn't work

### ISSUE THREAD

**Issue by yilingaifei** [gnosis/MultiSigWallet#267]
both of gnosis website wallet.gnosis.pm/.io  seem don't work correctly, firstly after I click unlock the wallet, my wallet address didn't appear on website, secondly, after I payed transcation fee(can't modify gas fee on website now), It keeps pending for a long time and will not show anything in wallet. Does anyone know how it happens? Is there anybody still keeping  update for this website?

**Comment by denisgranha** [comment]
I don't know why this happened to you, but could have been a temporal outage
