### ISSUE TITLE
npm install on windows

### ISSUE THREAD

**Issue by vrolland** [gnosis/MultiSigWallet#27]
Hello guys,

Very impressed by your job here!

Just install your multisgWallet dapp on windows and I had an issue. 
I fixed it on my side but I think it would be interesting to share it for the future windows users.
If you get "'.' is not recognize as an internal or external command"  -[screenshot](https://imgur.com/jGF1GjJ)- during the postinstall just change in the dapp/package.json the line : 
`"postinstall": "./node_modules/bower/bin/bower install && ./node_modules/grunt/bin/grunt ngtemplates",`
by
`"postinstall": "node ./node_modules/bower/bin/bower install && node ./node_modules/grunt/bin/grunt ngtemplates",`

Cheers,

**Comment by LachlanB96** [comment]
Fixed my exact same issue, cheers mate!

The file that needs changing for me was at C:\Users\<ME>\MultiSigWallet\dapp\package.json line 17

**Comment by yoscar1** [comment]
Hola @vrolland me podrias por favor indicar como correo la wallet. Ya la installe pero al hacer npm run test-dapp me da el siguiente error 
![image](https://user-images.githubusercontent.com/18383745/38632761-aa73ebfc-3d8b-11e8-996b-52efd2c2a4e4.png) y nose como correrla para probarla

**Comment by giacomolicari** [comment]
This is gonna be fixed with the next release.
