### ISSUE TITLE
erc20 daily limit

### ISSUE THREAD

**Issue by tamnich** [gnosis/MultiSigWallet#277]
I saw on Gnosis safe documation that it is possible to do a daily limit for erc20 token, but couldn't find it in the multisig UI (https://wallet.gnosis.pm) - do you plan to add this feature to the multisig wallet ? (not Gnosis safe)

**Comment by denisgranha** [comment]
Hi @tamnich the daily limit version is only for ether and we don’t plan to update multisig contracts for new features.

On the safe, there is a module that allows that.
