### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by miohtama** [gnosis/MultiSigWallet#28]
Looks like the hosted version certificate expired today. I assume the auto renewal did not kick in.

![image](https://user-images.githubusercontent.com/49922/31583703-c8bc26f2-b1a8-11e7-95c4-fc1db675ffee.png)

![image](https://user-images.githubusercontent.com/49922/31583705-d29691ee-b1a8-11e7-8c84-9d9b071118e1.png)

**Comment by giacomolicari** [comment]
Thanks for checking, solved.
