### ISSUE TITLE
This declaration shadows a builtin symbol.

### ISSUE THREAD

**Issue by N-B-V** [gnosis/MultiSigWallet#29]
Hi there,

Not sure if this wallet code is still a viable option but i'm trying to use it as a basis of my multisigwallet and i'm getting a few errors while trying to test the code in mist.
i'm using the code as found on -  https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol

After updating the pragma and all the instances of "throw" to "revert()" the following error when tryingto compile the MultiSigWallet.sol file in mist is.

 This declaration shadows a builtin symbol.
            Transaction tx = transactions[transactionId];
            ^------------^
, 

This references line 241.

thanks in advance for your feedback.

**Comment by rarigita** [comment]
Solved:
Replace the function executeTransaction(..){..} with:

function executeTransaction(uint transactionId)
        public
        ownerExists(msg.sender)
        confirmed(transactionId, msg.sender)
        notExecuted(transactionId)
    {
        if (isConfirmed(transactionId)) {
            Transaction storage txn = transactions[transactionId];
            txn.executed = true;
            if (txn.destination.call.value(txn.value)(txn.data))
                Execution(transactionId);
            else {
                ExecutionFailure(transactionId);
                txn.executed = false;
            }
        }
    }

I replaced all "tx" variables to "txn" and also inserted the word "storage" to avoid another warning thrown by the compiler... test and see if that works for you..

**Comment by N-B-V** [comment]
Thank you @rarigita that sorted out all the issues with the contract and i was able to compile it using https://ethfiddle.com/ without any issues.

**Comment by rarigita** [comment]
I'm just playing with the code now. Have you compiled into Ropsten and tested how it works? Maybe you can help me with that @N-B-V
