### ISSUE TITLE
How to log into Gitcoin using gnosis multisig

### ISSUE THREAD

**Issue by sulliwane** [gnosis/MultiSigWallet#299]
Hello Gnosis Team,

do you have any recommendation on how to interact with DApps using the Gnosis Multisig? As I can't "add gnosis multisig" to Metamask, I'm not sure how I'm supposed to proceed.

Thanks for your feedback!

**Comment by denisgranha** [comment]
My recommendation is to use the Gnosis Safe https://safe.gnosis.io/ it allows you to use a Multisig wallet with your browser and phone.
