### ISSUE TITLE
Truffle in package.json is missing?

### ISSUE THREAD

**Issue by rstormsf** [gnosis/MultiSigWallet#3]
I avoid having `truffle` binary installed globally and I'm dissappointed to see that it's not included in `package.json`
https://github.com/gnosis/MultiSigWallet/blob/truffle/package.json

because with latest truffle is not compilable.

```
            Transaction tx = transactions[transactionId];
            ^------------^
,/Users/rstorm/repos/MultiSigWallet/contracts/MultiSigWalletWithDailyLimit.sol:53:9: Warning: This declaration shadows a builtin symbol.
        Transaction tx = transactions[transactionId];
        ^------------^
,/Users/rstorm/repos/MultiSigWallet/contracts/MultiSigWallet.sol:241:13: Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.
            Transaction tx = transactions[transactionId];
            ^------------^
,/Users/rstorm/repos/MultiSigWallet/contracts/MultiSigWalletWithDailyLimit.sol:53:9: Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.
        Transaction tx = transactions[transactionId];
        ^------------^
Compiliation failed. See above.

```

./node_modules/.bin/truffle version
Truffle v3.4.9 (core: 3.4.8)
Solidity v0.4.15 (solc-js)

**Comment by rstormsf** [comment]
Just tried with older version:

```
Truffle v3.4.7 (core: 3.4.7)
Solidity v0.4.13 (solc-js)
```
and it works fine

**Comment by rstormsf** [comment]
compilation issue will be gone if I bump the version:
https://github.com/gnosis/MultiSigWallet/pull/4

**Comment by denisgranha** [comment]
Thanks for checking our code out, yeah solc compiler versions is something that breaks the code every month, would be nice that truffle supports different solc compiler versions
