### ISSUE TITLE
gasPrice / gasLimit completely ignored (LedgerWallet)

### ISSUE THREAD

**Issue by iivvoo** [gnosis/MultiSigWallet#30]
multisigweb on ubuntu (but also on Mac I suspect) seems to completely ignore gas settings. This results in expensive transactions, especially when the transaction fails (I paid $41 for a failed transaction)

Settings:

![msw-gas](https://user-images.githubusercontent.com/540122/31832619-f5a9ef82-b5c7-11e7-8222-88c2182515e8.png)

Results on actual transaction:

![msw-tr](https://user-images.githubusercontent.com/540122/31832650-1152928e-b5c8-11e7-8f5a-8190ec6d011e.png)

gasPrice does seem to vary sometimes but the limit is always around 6M

This issue appears similar to #23 but I use LederWallet and restarting has no effect.

**Comment by denisgranha** [comment]
We have added gas management for the last version of the interface

Previous versions, only used those values for the offline mode

**Comment by lisarice27** [comment]
I am trying to send tokens with the multisig and ledger.  I get no prompt for adjusting gas price and the transactions are getting mined.

**Comment by lisarice27** [comment]
Not getting mined.
