### ISSUE TITLE
Added wallet with 1.4.1. Upgrade to 1.6.0 and wallet is gone, and cannot add wallet again

### ISSUE THREAD

**Issue by phuongnd08** [gnosis/MultiSigWallet#301]
![multisigweb-bugs](https://user-images.githubusercontent.com/184037/64485049-4c86f480-d245-11e9-8366-6a680363641b.gif)

There should be some visible logging to see what's going on? RIght now I'm clueless

**Comment by denisgranha** [comment]
Hi @phuongnd08 !

Most likely this has relation with the URL used for the ethereum node, please check this https://www.gitmemory.com/issue/gnosis/MultiSigWallet/241/484710674

**Comment by phuongnd08** [comment]
On 1.6.0 when I select custom node all i got is this:
![image](https://user-images.githubusercontent.com/184037/64681520-11d1c600-d4aa-11e9-996e-06e7781b02e2.png)

There was no dialog asking for a url.

**Comment by giacomolicari** [comment]
Hi @phuongnd08 ,
try the following: 
https://github.com/gnosis/MultiSigWallet#how-to-set-a-custom-ethereum-node

Hope that helps.

**Comment by phuongnd08** [comment]
Okay, I think I successfully set the Ethereum node to my node today.
But whenever I tried to propose or confirm anything, all I got is executing button that going forever
![image](https://user-images.githubusercontent.com/184037/65023048-46d39200-d95c-11e9-9343-c9a98bfa3600.png)

**Comment by phuongnd08** [comment]
Okay, the problem is wallet in 1.6.0 need to be checksum-ed. I re-add the wallet and I can see my transaction now.
