### ISSUE TITLE
Issue on Dektop App - This wallet was created on another chain

### ISSUE THREAD

**Issue by zisis19** [gnosis/MultiSigWallet#303]
Suddenly in the last 1 month when i connect to the desktop app, i cannot get the wallet information to load properly and i keep getting the exclamation mark at the left with this message: " This wallet was created on another chain". On the browser all is working properly but I am facing this issue on the desktop app. I am using the same computer and environment as before so I am really puzzled on what is going on. Any ideas?

**Comment by postables** [comment]
Getting this issue as well :/
