### ISSUE TITLE
Adding/Removing Owners

### ISSUE THREAD

**Issue by susruth** [gnosis/MultiSigWallet#31]
Is it possible to add or remove owners? When I am trying to submit a transaction with pre-crafted data to add a user, It runs out of gas (during the execution part). It sents 0 gas for some reason(As I checked in the parity trace on [etherscan.io](https://ropsten.etherscan.io/vmtrace?txhash=0x4c707894cdd4b369489df32f9923acd186dc66df0f525ad4c0ec5c74e6fb6dc2&type=parity)) I am testing this on Ropsten, and I could not find any way to add/remove owners in the gnosis web app as well. It looks like it has been built into the contract but is not possible to use. Am I missing something? Thanks.

**Comment by reiven** [comment]
Hi @susruth i runned into the same problem, and if the problem is the 'out of gas' for the function execution i suggest you to re-call the *executeTransaction()* function raising the suggested gas and i will execute correctly

**Comment by susruth** [comment]
Thanks @reiven for the reply, but I tried doing that and it still the executeTransaction creates a transaction with 0 gas. It works well for all the contract calls I tested and has this problem only when sending a transaction to itself.

**Comment by denisgranha** [comment]
you cannot rely on estimateGas or default node gas for inner calls
You need to pass the gas manually, for adding/removing an owner you need around 300k gas
