### ISSUE TITLE
Page not found - The resource you're looking for doesn't exist.

### ISSUE THREAD

**Issue by Enigmatic331** [gnosis/MultiSigWallet#310]
When clicking on a deployed multisignature wallet to view its owners etc, a page not found error is returned on version 1.6.0.

v1.6.0
![image](https://user-images.githubusercontent.com/28551011/65768216-eebe3c00-e162-11e9-9590-c7bf2831e148.png)

v1.3.7
![image](https://user-images.githubusercontent.com/28551011/65768236-fe3d8500-e162-11e9-9ca3-04c1bc413afc.png)

Will continue testing between versions to see if I could identify from which version it broke for me.

**Comment by Enigmatic331** [comment]
Ah. Should be due to this PR - So I'll need to re-add the addresses: https://github.com/gnosis/MultiSigWallet/commit/237a7f2066cb4b35913bbd5dd6db2ecac9dd0e7f

Probably not ideal since from a user PoV sees "something breaks when I upgrade", but I guess I could live with it.

**Comment by denisgranha** [comment]
yes, it was an accidental Break change, 

Sorry for the inconvennience
