### ISSUE TITLE
Dapper mobile fails to connect.

### ISSUE THREAD

**Issue by zimlokks** [gnosis/MultiSigWallet#337]
After the most recent update, which introduced hardware wallet support, Dapper mobile hasnt been able to connect with my safe. 

The web page detects dapper but can't connect with it.

Any other info I can provide please ask.

OnePlus 6T 
Lineage OS 17.1 beta

**Comment by lukasschor** [comment]
I assume this is related to github.com/gnosis/safe-react ?

This repo is for the old version of the Gnosis Multisig
