### ISSUE TITLE
onlyWallet() modifier understanding

### ISSUE THREAD

**Issue by AndriyYakymiv** [gnosis/MultiSigWallet#34]
Hello,
I was trying to understand how **MultiSigWallet.sol** is working and have noticed that `addOwner(address owner)` function calls the `submitTransaction(address destination, uint value, bytes data)` function on this contract when you post transaction for signing, and into the data field passes a data (probably generated bytecode of  `addOwner(address owner)` function), which will be deployed into the blockchain when transaction will be confirmed and executed. Then I deployed the same contract, but for `addOwner(address owner)` function I had removed `onlyWallet()` modifier and calling the `addOwner(address owner)` function at this time (when I was posting a transaction for signing) showed me that I'm going to execute `addOwner(address owner)` function on this new smart contract in contradistinction to `submitTransaction(address destination, uint value, bytes data)`  for previous one. 
So, the question is : how does this modifier affects on function calling process and "calls" the  `submitTransaction(address destination, uint value, bytes data)`?

**Comment by abbbe** [comment]
onlyWallet modifier is required to make addOwner a multisigned transaction, which is critical for security.

**Comment by denisgranha** [comment]
The onlyWallet modifier it's needed for limiting the multisig transactions to be only executed after submitTransaction and confirmTransaction

Without the onlyWallet modifier, one owner could change everything without the other owners confirmation

**Comment by night18** [comment]
Does onlyWallet() modifier have the same function of "private" ?
