### ISSUE TITLE
Found a bug when send multisig transactions

### ISSUE THREAD

**Issue by xuxiao415** [gnosis/MultiSigWallet#45]
my contract has one function `setTransferable(bool _transferable)`, when send a multisig transaction to call the function with false argument(the variable of transferable is true before calling the function), the result is not expected. The variable of transferable is still true. when I see the transaction in etherscan, I found the argument passed is not false but true. So, I think the function that getting data from input box works wrong, it doesn't parse the false .

**Comment by denisgranha** [comment]
can you add a bit more of context? sources and link to tx's would be great

**Comment by denisgranha** [comment]
hi @xuxiao415 can you provide more info, like tx links?
Thanks

**Comment by phaldenby** [comment]
Found the same bug.
Whenever you try to pass false as an argument to a function that takes a boolean, gnosis multisig will pass in true.

**Comment by ahnaguib** [comment]
This bug exists in both web UI and mac client. a boolean parameter called using the interface is set to true regardless of the value in the input field. I am not including a tx as requested above because, it won't show anything useful(The issue has to reproduced using the UI)

**Comment by wighawag** [comment]
I can confirm the bug still exists.
Any function that have a bool as input in its ABI will always treat the user input as a true value,
I tried setting the field to "false" false, "0x0", 0 but the interface always create a transaction with a true value.
Also in the transaction summary it shows the following for the value use : `{{param.value\|addressCanBeOwner:wallet\|addressCanBeToken:wallet\|logParam}}`

**Comment by wighawag** [comment]
The fix would involve parsing the field when the ABI input is a bool
So for example this could be done like you parse arrays here : https://github.com/gnosis/MultiSigWallet/blob/22586a4ed13d2dde8980dfceaeb717143e87ffc9/dapp/src/controllers/walletTransactionCtrl.js#L105

**Comment by Xychun** [comment]
+1 Please reopen issue and fix.
