### ISSUE TITLE
Manage Notifications link doesn't work

### ISSUE THREAD

**Issue by madvas** [gnosis/MultiSigWallet#46]
![image](https://user-images.githubusercontent.com/3857155/34642653-08c8761a-f317-11e7-9f1c-e5dcb1b94075.png)

Leads to https://wallet.gnosis.pm/%7B%7BalertManagementPage%7D%7D , which doesn't work.

**Comment by denisgranha** [comment]
Hi @madvas the notification system has been disabled in the last version and we don't plan to enable it again in the near future
