### ISSUE TITLE
In wallet with 3 parties, withdrawal allows single party, even though 2 parties did not confirm.

### ISSUE THREAD

**Issue by chuacw** [gnosis/MultiSigWallet#49]
I have a Gnosis wallet on Ropsten, that has 3 parties required to confirm, however, when withdrawing, it appears 1 party can withdraw (up to daily limit), without the consent/confirmation of the 2 parties.

Is this as designed, or is there a bug?

**Comment by denisgranha** [comment]
Good afternoon,

You have a multisig with daily limit, if this limit is greater than 0, owners can withdraw ether below the limit without other confirmations.

Set the daily limit to 0 if you want to require confirmations for all txs

Best,

Denis

**Comment by chuacw** [comment]
@denisgranha But the "Withdraw" button is disabled when the limit is set to 0?

**Comment by denisgranha** [comment]
Yes, this is a know issue that will be solved in an upcoming update this week,

In the meantime you can perform the transaction by clicking on the wallet name in the wallet list > Add (Multisig transaction) > Value enter the amount you want to withdraw and to, the destionation address

Best,

Denis

**Comment by denisgranha** [comment]
Hello @chuacw it's enabled now even when the daily limit is 0

Best,
