### ISSUE TITLE
Wallet owner too powerful

### ISSUE THREAD

**Issue by Asoul** [gnosis/MultiSigWallet#52]
Hi, I view the contract and find out that the `removeOwner` and `addOwner` action is not a majority, but the wallet owner can decide which address to add and remove. That means if someone is the wallet owner, who can remove all other owners, then execute any transactions.

Is that correct? or I misunderstood that?

I think a better idea is that the `addOwner` and `removeOwner` function should use the majority system or even need everyone's agreement, then if the wallet owner is compromised, the whole wallet is still temporarily safe.

**Comment by denisgranha** [comment]
Hi Asoul,

The only one that can execute the addOwner and removeOwner it's the wallet itself, that means that it needs to be executed by the multisig function executeTransaction, in order to execute transaction go forward it needs all the required confirmations of the owners

**Comment by Asoul** [comment]
Thank you @denisgranha !
