### ISSUE TITLE
Latest Mac Ver (01/26/2018) cannot detect ledger wallet

### ISSUE THREAD

**Issue by xiaoyao1991** [gnosis/MultiSigWallet#63]
I found that the latest Mac version of the wallet on gnosis website cannot detect ledger wallet, which is weird. The ledger wallet firmware is 1.3.1. In the earlier version, I can plug in my ledger and the gnosis wallet will automatically detect, but in the latest version, it doesn't work. The ledger wallet also didn't show "confirm address" either.

**Comment by denisgranha** [comment]
Hi @xiaoyao1991 thanks for reporting it, it's solved in the release https://github.com/gnosis/MultiSigWallet/releases/tag/1.1.0
