### ISSUE TITLE
Sending Transactions with 1 confirmation

### ISSUE THREAD

**Issue by backslash05** [gnosis/MultiSigWallet#67]
I have set up a test wallet on Kovan that requires 2 confirmations. As soon as i send the transaction, it never asks any other account for confirmation and just sends the eth. Am i missing something here?

**Comment by mimoo** [comment]
same thing here on Ropsten

**Comment by denisgranha** [comment]
Hi @backslash05 the multisig has one parameter called daily limit, that's the amount of ETH that one owner can withdraw with only one confirmation (his own confirmation) set it to 0 if you want to avoid that
