### ISSUE TITLE
Now withdraw has no gasprice interface. . .

### ISSUE THREAD

**Issue by playcode001** [gnosis/MultiSigWallet#69]
Now withdraw has no gasprice interface. . .

**Comment by denisgranha** [comment]
what version are you using?

**Comment by playcode001** [comment]
OSX-x64-1.1.1
Setting gasprice automatically does not work well。

**Comment by playcode001** [comment]
@denisgranha 
OSX-x64-1.1.1
Setting gasprice automatically does not work well。

**Comment by denisgranha** [comment]
Hi @playcode001 please try the latest version https://github.com/gnosis/MultiSigWallet/releases/tag/v1.2.1
You shouldn't have those problems
