### ISSUE TITLE
Gas problem. Withdraw pending for 16 hours

### ISSUE THREAD

**Issue by kinhunt** [gnosis/MultiSigWallet#70]
I am trying to use this for company funds. Everything seems to be working fine until I submitted a withdraw with default recommended gas settings. 

The transaction has been pending for more than 16 hours. 

My question is, should I use the default recommended gas setting? If not, how to set the gas.

https://etherscan.io/tx/0xdda2d9ff1b1dd1c7cab2e5c4a3386a9fc945f5c13fde5e39324a4483adeae408

Thank you.

**Comment by denisgranha** [comment]
Hi Kinhunt,

The gas price used by default is taken from https://ethgasstation.info

You can check here the different values for gas price and the estimated time for mining

Is an estimation, it might happen, as it was your case, that the tx is never mined that you need to send a tx again.
