### ISSUE TITLE
In chrome the wallet is freaking out

### ISSUE THREAD

**Issue by GriffGreen** [gnosis/MultiSigWallet#71]
I can't get it to load any more... :-( in chrome this is all I get:

<img width="1326" alt="screen shot 2018-02-04 at 10 51 18 pm" src="https://user-images.githubusercontent.com/14945613/35779337-fa265368-09fd-11e8-97ca-8aaba5dddef5.png">

In Brave, i can see the first screen... but i cant see the wallet's information:
<img width="1021" alt="screen shot 2018-02-04 at 11 51 32 pm" src="https://user-images.githubusercontent.com/14945613/35780025-8994acf2-0a08-11e8-8579-b79d6a585d65.png">
<img width="1013" alt="screen shot 2018-02-04 at 11 51 12 pm" src="https://user-images.githubusercontent.com/14945613/35780028-89c884dc-0a08-11e8-92e3-86f390e42147.png">

**Comment by denisgranha** [comment]
Mmm, can you share the browser console output?

What provider are you using? metamask?

**Comment by GriffGreen** [comment]
Oops! Sorry! Yes Metamask :-D


Brave:
<img width="775" alt="screen shot 2018-02-05 at 12 08 41 am" src="https://user-images.githubusercontent.com/14945613/35808467-6aa31882-0ab8-11e8-8311-f29ed3fea169.png">

Chrome:
![screen shot 2018-02-05 at 9 09 41 pm](https://user-images.githubusercontent.com/14945613/35808608-ea45821e-0ab8-11e8-8b58-9fcdaa31c1c4.png)

**Comment by GriffGreen** [comment]
the settings page doesnt load


<img width="1383" alt="screen shot 2018-02-23 at 9 00 44 pm" src="https://user-images.githubusercontent.com/14945613/36614443-08f41856-18dd-11e8-9390-ce8f2c8dde94.png">
<img width="673" alt="screen shot 2018-02-23 at 8 59 40 pm" src="https://user-images.githubusercontent.com/14945613/36614444-09116ffa-18dd-11e8-872d-5b9e4a94c464.png">

(index):58 [Violation] Avoid using document.write().
(anonymous) @ (index):58
2(index):58 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ (index):58
config.js:159 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at checkWalletFactoryAddress (config.js:159)
    at config.js:173
checkWalletFactoryAddress @ config.js:159
(anonymous) @ config.js:173
angular.js:4669 Uncaught TypeError: Cannot read property 'checkInterval' of undefined
    at setup (Connection.js:14)
    at new <anonymous> (Connection.js:32)
    at Object.instantiate (angular.js:4733)
    at Object.<anonymous> (angular.js:4573)
    at Object.invoke (angular.js:4718)
    at Object.$get (angular.js:4557)
    at Object.invoke (angular.js:4718)
    at angular.js:4517
    at d (angular.js:4664)
    at e (angular.js:4688)
setup @ Connection.js:14
(anonymous) @ Connection.js:32
instantiate @ angular.js:4733
(anonymous) @ angular.js:4573
invoke @ angular.js:4718
(anonymous) @ angular.js:4557
invoke @ angular.js:4718
(anonymous) @ angular.js:4517
d @ angular.js:4664
e @ angular.js:4688
instantiate @ angular.js:4730
(anonymous) @ angular.js:4573
invoke @ angular.js:4718
(anonymous) @ angular.js:4557
invoke @ angular.js:4718
(anonymous) @ angular.js:4517
d @ angular.js:4664
e @ angular.js:4688
invoke @ angular.js:4710
(anonymous) @ angular.js:4526
q @ angular.js:321
cb @ angular.js:4526
c @ angular.js:1758
Bc @ angular.js:1779
fe @ angular.js:1664
(anonymous) @ angular.js:31763
b @ angular.js:3207
Sf @ angular.js:3497
d @ angular.js:3485
DomManipulator.js:7 Init EAL
/#/settings:1 The SSL certificate used to load resources from https://api.webtest.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by GriffGreen** [comment]
but it does work in incognito :-D maybe you can tell me what cashed file i need to delete :-D

**Comment by denisgranha** [comment]
Mmm, I think I know what happens, in localStorage, there is one parameter config, one of it's properties must be null, walletFactoryAddress

You can try to remove that value from localStorage, or email me that object to denis@gnosis.pm and will add a check for that
