### ISSUE TITLE
Key export fails (OSX)

### ISSUE THREAD

**Issue by sillytuna** [gnosis/MultiSigWallet#73]
Exporting a key stays stuck in Executing on OSX. It can be cancelled  but the key can never export.

EDIT: Bug also exists on Windows.

**Comment by MatthewJPritchard** [comment]
I'm also experiencing this issue on Windows 10 installations. It works on Windows 7 however.

**Comment by peterturquoise** [comment]
Same for me on OSX & Windows 10. 

Obviously it's CRUCIAL to be able to back up a multisig key - can someone get back ASAP about this please. Did either of you other guys find a workaround.

**Comment by peterturquoise** [comment]
It's the app version. I re-installed the older one (size 69.6MB on OSX) and that works as expected, but the latest version (77.5MB on OSX) just shows the "Executing..." message . 

BTW how does the wallet recover its accounts after I delete it and re-install it?

**Comment by denisgranha** [comment]
Solved in https://github.com/gnosis/MultiSigWallet/commit/586f11ff8e28a9b2cbea701248261719fdbcebe7 will have a new release shortly

**Comment by denisgranha** [comment]
https://github.com/gnosis/MultiSigWallet/releases/tag/v1.2.1
