### ISSUE TITLE
Overflow and termination issue

### ISSUE THREAD

**Issue by wuestholz** [gnosis/MultiSigWallet#81]
I noticed an issue in function `getTransactionIds` of the `MultiSigWallet` contract: if the `from` argument is greater than the `to` argument the [subtraction on line 366](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L366) will overflow, creating a very large array. Independently, this would also result in the subsequent loop not terminating for a very long time.

I would suggest that you add more parameter validation at the beginning of the method body to prevent this (e.g., `require(from <= to)` or `require(from < to)` depending on the intended semantics).

**Comment by denisgranha** [comment]
They @wuestholz thanks for reviewing the code :)
This function is never used by any transaction, it's just a helper function for easier integration with frontend, only used for read operations

**Comment by wuestholz** [comment]
@denisgranha I see. Thanks for looking into it!
