### ISSUE TITLE
Can't re-add deleted account

### ISSUE THREAD

**Issue by peterturquoise** [gnosis/MultiSigWallet#83]
I deleted an account but when I tried to re-add it the wallet told me I couldn't as the account was already there. I noticed the account WAS in a wallet, but it wasn't in the list of accounts.

Any way to fix this ?

**Comment by denisgranha** [comment]
Hello @peterturquoise what version are you using, I guess the desktop with lightwallet as key manager?
Which OS ?

Thanks

**Comment by peterturquoise** [comment]
Thanks Denis

I had the problem on OS X but I didn’t try it on Windows Yes I was using
lightwallet

Incidentally - when I delete the app from my machine and reinstall it, it
somehow picks ‘remembers’ all the previous wallets and accounts - how dies
it do this? Is there a file somewhere that it stores the accounts & wallets
? If so where is that file on OSX and Windiws?

Appreciate the help

BR
Peter

**Comment by denisgranha** [comment]
Hello Peter,

It's a electron app, with almost the same code than the web version, it stores the encrypted keys on localstorage of the app.

If you wan't to avoid that I recommend using a Ledger

**Comment by denisgranha** [comment]
with which version did you have that problem @peterturquoise ?

Warm regards,

**Comment by peterturquoise** [comment]
Denis,

 Where I said "it's an electron app' that was iOS speak for "it's an OSX
app"

I couldn't find a way to display the app version info on the app so below
is its info.plist .

It would be super useful to have access to the version on the app directly


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>BuildMachineOSBuild</key>
        <string>15G31</string>
        <key>CFBundleDisplayName</key>
        <string>multisigweb</string>
        <key>CFBundleExecutable</key>
        <string>multisigweb</string>
        <key>CFBundleIconFile</key>
        <string>multisigweb.icns</string>
        <key>CFBundleIdentifier</key>
        <string>pm.gnosis.wallet</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>multisigweb</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>1.0.0</string>
        <key>CFBundleVersion</key>
        <string>1.0.0</string>
        <key>DTSDKBuild</key>
        <string>14D125</string>
        <key>DTSDKName</key>
        <string>macosx10.1010.10</string>
        <key>DTXcode</key>
        <string>0821</string>
        <key>DTXcodeBuild</key>
        <string>8C1002</string>
        <key>LSApplicationCategoryType</key>
        <string>public.app-category.developer-tools</string>
        <key>LSMinimumSystemVersion</key>
        <string>10.9.0</string>
        <key>NSHighResolutionCapable</key>
        <true/>
        <key>NSMainNibFile</key>
        <string>MainMenu</string>
        <key>NSPrincipalClass</key>
        <string>AtomApplication</string>
        <key>NSSupportsAutomaticGraphicsSwitching</key>
        <true/>
        <key>NSHumanReadableCopyright</key>
        <string>Copyright © 2017 Gnosis</string>
    </dict>
</plist>

Thanks again for your help

BR

Peter

**Comment by denisgranha** [comment]
Adding of deleted accounts is fixed in https://github.com/gnosis/MultiSigWallet/releases/tag/v1.2.1

**Comment by peterturquoise** [comment]
Thanks Denis,

appreciate the feedback

BR

Peter
