### ISSUE TITLE
Overflow and termination issue in getter function

### ISSUE THREAD

**Issue by maurelian** [gnosis/MultiSigWallet#84]
A relatively minor issue, but wanted to inform you. See the original report here:
https://github.com/ConsenSys/MultiSigWallet/issues/2#issuecomment-367778274 

Same item in this repository:
https://github.com/gnosis/MultiSigWallet/blob/350630d701a71bb7aa883b68167b678b7722b9f7/contracts/MultiSigWallet.sol#L366

**Comment by denisgranha** [comment]
Hey @maurelian I think I already commented you in another channel, thx for the info:

This is not a vulnerability because this function it's only used by frontend, doesn't mind to have overflow here

Thx
