### ISSUE TITLE
UI changes owner names even without required confirmations

### ISSUE THREAD

**Issue by D-Nice** [gnosis/MultiSigWallet#89]
Any owner can change the name of another owner, and the change will be immediately reflected in the UI, even without sufficient confirmations. See:

![image](https://user-images.githubusercontent.com/2888248/36993520-101bd2e4-207c-11e8-8439-eda32a4db42c.png)

2 confirmations are required

Even revocation of the name update, leaves the name in the UI. Only thing that resets it is attempting to replace the owner (Resets back to `Owner N`, or of course updating the name again.

**Comment by reiven** [comment]
Thats correct @D-Nice because you are just changing the 'friendly name' of the address, not the address of the owner. Changing addresses needs a transaction and confirmation of the need amount of signer to be executed.

**Comment by D-Nice** [comment]
Got it thanks, was not sure if this was the intended behaviour.
