### ISSUE TITLE
Cannot read property 'encrypt' of undefined

### ISSUE THREAD

**Issue by sivagopaltech** [gnosis/MultiSigWallet#92]
I have a generated a JSON file of my account using the following code

var Wallet = require('ethereumjs-wallet');
var key = Buffer.from('myprivatekey', 'hex');
var wallet = Wallet.fromPrivateKey(key);
var keystore = wallet.toV3String('sivagopal', { n: 1024 });

when imported the file in myetherwallet it works fine but when I imported in my multisigclient for ubuntu its throwing following error
**Cannot read property 'encrypt' of undefined**

**Comment by jsnx** [comment]
same here.

**Comment by denisgranha** [comment]
Yeah, that was due to break change in on of the dependencies, it's solved on the last releases
