### ISSUE TITLE
MultiSig Walkthru

### ISSUE THREAD

**Issue by dclancy13** [gnosis/MultiSigWallet#94]
Hey! 
I'm a multisig noob and am looking for a somewhere I can get a basic walkthrough of how to set up and use the Gnosis wallet? I downloaded the GUI for Mac and it's not allowing me to create a new wallet. I can only restore. 

<img width="982" alt="screen shot 2018-03-13 at 09 48 53" src="https://user-images.githubusercontent.com/16654194/37345675-d54d58ee-26a3-11e8-9d75-45c38674a3b8.png">

Really I haven't been able to find much info at all on how to use the Gnosis wallet, is it somewhere and I'm just missing it? 

Thanks for the help

**Comment by denisgranha** [comment]
Hello @dclancy13 unfortunately there are no official docs on how to use the Multisig, but feel free to ask you questions at https://gitter.im/gnosis/MultiSigWallet?source=orgpage
