### ISSUE TITLE
Contract code not verified on etherscan

### ISSUE THREAD

**Issue by GriffGreen** [gnosis/MultiSigWallet#99]
https://etherscan.io/address/0x37f25bd26848cf02614c29338dd71a4d03b62218#code

I just deployed this Multisig but its not verified on etherscan... Can you provide the contract code so I can verify it... ? Or Verify it for me :-D

Much Love!
Griff

**Comment by billsinc** [comment]
https://etherscan.io/verifyContract?a=0x37f25bd26848cf02614c29338dd71a4d03b62218 depending on which you used the code is here, https://github.com/gnosis/MultiSigWallet/tree/master/contracts

**Comment by GriffGreen** [comment]
Thx @billsinc for the response!! I obv can make this work, but is there not an easy one stop shop for verifying this multisig? Like 1 file with the entire code set in there and a couple steps written out for end users to follow... like a blog post?

If there isn't I'll set a giveth contributor on it... but i dont want to recreate work.

**Comment by deamme** [comment]
Wrote a more general and in-depth guide here: https://medium.com/@Deam/verifying-a-contract-triggered-by-another-contract-on-etherscan-io-96a8c5a0ac2.
And and also a more straightforward and simple guide here: https://medium.com/@Deam/verifying-gnosis-multisig-contract-on-etherscan-io-c87dcb32893c

**Comment by GriffGreen** [comment]
@billsinc the super trimmed down automatic walk thru is here (with a video) is here: https://twitter.com/Givethio/status/982251966926544897?s=19

**Comment by denisgranha** [comment]
Hey @GriffGreen , so you must have been using a custom factory contract, maybe some testnet one, and when changing to mainnet the interface didn't detect any factory contract available at that address, so deployed it directly, without factory
